### PR TITLE
Add a link to JME reference under variable definition box

### PR DESCRIPTION
**Pull request by janga1997**
@christianp I hope this is ok.
And on a separate note, why do all these changes on different lines show up even when I did not touch them?

### CODE REVIEW

**Comment by janga1997** [comment]
@christianp I don't understand. What conflicts could there possibly be? I added a simple `<a>`.

**Comment by christianp** [comment]
I think your editor is removing trailing whitespace from the ends of every line in each file you edit. Which editor are you using?

Ideally, there shouldn't be any trailing whitespace in the repo, but since there is, fixing it should be a separate commit.

**Comment by janga1997** [comment]
@christianp I am using Atom. how do i rectify this?

**Comment by christianp** [comment]
Looks like you need to change the settings of the Whitespace package: untick "Remove trailing whitespace" https://github.com/atom/whitespace/issues/10#issuecomment-85183781

**Comment by christianp** [comment]
Thanks, but the link is in the wrong place - you've got it to the left of the **Value** label:

image

The link should go *below* the codemirror textarea, and only appear when `templateType().id=='anything'` (i.e. under line 231 of `editor/templates/question/edit.html`, currently)

Have you got the editor running locally?

**Comment by janga1997** [comment]
@christianp I've been putting off running the editor locally for some time. Think I have to do it to get serious.

**Comment by christianp** [comment]
This has been completed in #364

**Pull request closed without merging**
