### PR TITLE
Disable edit controls on exam based on permissions

### PR DESCRIPTION
**Pull request by docoleman**
Add editable checks for the group name input field, remove group button
and add question group button, they will be disabled when the user
does not have permission to edit the exam.

### CODE REVIEW

**Comment by docoleman** [comment]
fixes #449

**Comment by christianp** [comment]
Super, thanks!

**Comment by christianp** [comment]
Can you add yourself to the file `CONTRIBUTORS.md`, please?

**Comment by docoleman** [comment]
I've created a new pull request (#462) for the changes to `CONTRIBUTORS.md`. Thanks!

**Pull request merged**
